version: '2'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
  redis:
    image: redis:3.2.4
    ports:
      - "6379:6379"
  postgres:
    image: postgres:8
    ports:
      - "5432:5432"
  fluentd:
    image: fluent/fluentd
    ports:
      - "24224:24224"
      - "5140:5140"
    volumes:
      - ./fluentd:/fluentd/etc
      - ./fluentd/log:/fluentd/log
    environment:
      FLUENTD_CONF: fluentd.conf
